[package]
name = "taco"
version = "1.0.2"
edition = "2021"

[dependencies]
ollama-rs = {version = "0.2.0", features = ["chat-history"]}
lazy_static = "1.5.0"
serenity = "0.12.2"
tokio = { version = "1.43.1", features = ["macros", "rt-multi-thread"] }